---
language: scala
script: "sbt coveralls"
jdk:
- oraclejdk7
- openjdk7
scala:
- 2.10.2
branches:
    only:
        - master
        - development
notifications:
    email:
        - ivan.kuraj@gmail.com